[workspace]
members = [
	"mountpoint-s3-crt",
	"mountpoint-s3-crt-sys",
	"mountpoint-s3-client",
	"mountpoint-s3",
	"mountpoint-s3-fuser",
	"mountpoint-s3-fs",
]
resolver = "2"

[profile.release]
debug = 2
split-debuginfo = "off" # keep the debug info in the binary
