[package]
name = "fuse"
version = "0.2.8"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
build = "build.rs"
description = "Rust library for filesystems in userspace (FUSE)"
documentation = "https://docs.rs/fuse"
homepage = "https://github.com/zargony/rust-fuse"
repository = "https://github.com/zargony/rust-fuse"
readme = "README.md"
keywords = ["fuse", "filesystem", "system", "bindings"]
license = "MIT"

[build-dependencies]
pkg-config = "^0.3.7"

[dependencies]
libc = "0.2"
log = "0.3"
time = "0.1"
thread-scoped = "1.0"

[dev-dependencies]
env_logger = "0.3"

[lib]
name = "fuse"
path = "src/lib.rs"
