[package]
name = "mountpoint-s3-crt"
# See `/doc/PUBLISHING_CRATES.md` to read how to publish new versions.
version = "0.13.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/awslabs/mountpoint-s3"
description = "Rust interface to the AWS Common Runtime for Mountpoint for Amazon S3."

[dependencies]
mountpoint-s3-crt-sys = { path = "../mountpoint-s3-crt-sys", version = "0.15.0" }

aws-credential-types = "1.2.1"
aws-sdk-s3control = "1.86.0"
futures = "0.3.31"
libc = "0.2.174"
log = "0.4.27"
smallstr = "0.3.0"
static_assertions = "1.1.0"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["rt", "macros", "rt-multi-thread"] }

[dev-dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
clap = { version = "4.5.40", features = ["derive"] }
criterion = "0.6.0"
ctor = "0.4.2"
rand = { version = "0.8.5", features = ["small_rng"] }
serde_json = "1.0.140"
test-case = "3.3.1"
tracing = { version = "0.1.41", default-features = false, features = ["std", "log"] }
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }

[[bench]]
name = "event_loop_future"
harness = false

[[bench]]
name = "checksums"
harness = false
