[package]
name = "mountpoint-s3-crt"
# See `/mountpoint-s3-client/PUBLISHING_CRATES.md` to read how to publish new versions.
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/mountpoint-s3"
description = "Rust interface to the AWS Common Runtime for Mountpoint for Amazon S3."

[dependencies]
mountpoint-s3-crt-sys = { path = "../mountpoint-s3-crt-sys", version = "0.10.0" }

futures = "0.3.31"
libc = "0.2.168"
log = "0.4.22"
smallstr = "0.3.0"
static_assertions = "1.1.0"
thiserror = "2.0.6"

[dev-dependencies]
anyhow = { version = "1.0.94", features = ["backtrace"] }
clap = { version = "4.5.23", features = ["derive"] }
criterion = "0.5.1"
ctor = "0.2.9"
rand = { version = "0.8.5", features = ["small_rng"] }
serde_json = "1.0.133"
test-case = "3.3.1"
tracing = { version = "0.1.41", default-features = false, features = ["std", "log"] }
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }

[[bench]]
name = "event_loop_future"
harness = false

[[bench]]
name = "checksums"
harness = false
