[package]
name = "mountpoint-s3-crt"
# See `/mountpoint-s3-client/PUBLISHING_CRATES.md` to read how to publish new versions.
version = "0.6.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/mountpoint-s3"
description = "Rust interface to the AWS Common Runtime for Mountpoint for Amazon S3."

[dependencies]
mountpoint-s3-crt-sys = { path = "../mountpoint-s3-crt-sys", version = "0.5.3" }

async-channel = "1.8.0"
futures = "0.3.24"
libc = "0.2.132"
log = "0.4.17"
smallstr = "0.3.0"
static_assertions = "1.1.0"
thiserror = "1.0.35"

[dev-dependencies]
criterion = "0.5.1"
ctor = "0.1.23"
futures-timer = "3.0.2"
rand = { version = "0.8.5", features = ["small_rng"] }
tempfile = "3.4.0"
test-case = "2.2.2"
tracing-subscriber = { version = "0.3.14", features = ["fmt", "env-filter"] }

[[bench]]
name = "event_loop_future"
harness = false

[[bench]]
name = "checksums"
harness = false
