name: Benchmarks (PR)

on:
  pull_request_target:
    types: [ labeled, opened, reopened, synchronize ]

permissions:
  id-token: write
  contents: write # required by bench.yml and bench_s3express.yml even if we don't actually publish the results to gh-pages for PRs

jobs:
  integration:
    name: Benchmarks
    uses: ./.github/workflows/bench.yml
    if: ${{ contains(github.event.pull_request.labels.*.name, 'performance') }}
    with:
      environment: PR benchmarks
      ref: ${{ github.event.pull_request.head.sha }}
      # store results with prefix defined by PR id (github.event.number)
      s3_bench_results_prefix: ${{ github.event_name == 'pull_request_target' && format('results/{0}/s3_standard', github.event.number) || null }}
  s3express-integration:
    name: Benchmarks (s3express)
    uses: ./.github/workflows/bench_s3express.yml
    if: ${{ contains(github.event.pull_request.labels.*.name, 'performance') }}
    with:
      environment: PR benchmarks
      ref: ${{ github.event.pull_request.head.sha }}
      # store results with prefix defined by PR id (github.event.number)
      s3_bench_results_prefix: ${{ github.event_name == 'pull_request_target' && format('results/{0}/s3_express', github.event.number) || null }}
