name: Release

on:
  push:
    tags:
      - mountpoint-s3-[0-9]+.*

permissions:
  contents: write


jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/create-gh-release-action@v1
      with:
        title: "mountpoint-s3 v$version"
        # Strip this prefix off the tag to discover the version number
        prefix: mountpoint-s3
        draft: true
        changelog: mountpoint-s3/CHANGELOG.md
        # TODO: make this mandatory once we have the format nailed down
        allow-missing-changelog: true
        branch: main
        token: ${{ secrets.GITHUB_TOKEN }}
